### ISSUE TITLE
hi, i have a trouble. How to fix it

### ISSUE THREAD

**Issue by kobiethackfacebook** [dejanmauer/CSharpChain#1]
[
![xoa](https://user-images.githubusercontent.com/46417165/58342652-306c6c80-7e7b-11e9-8b23-9010d1ae5907.PNG)
](url)

**Comment by dejanmauer** [comment]
It is difficult to tell the reason from the picture, as it is too small to read...

**Comment by kobiethackfacebook** [comment]
Vào Th 2, 27 thg 5, 2019 lúc 13:50 Dejan <notifications@github.com> đã viết:

> thanks, i fixed but i don't understand "List<string> Nodes"  in your
> project for what.
> [image: xoa.PNG]
>
 - my name is Hoan and I'm Vietnamese, I am doing on a blockchain topic, I
hope you can help me, My English is not good so i sorry if it's wrong ^^

**Comment by dejanmauer** [comment]
CSharpChain is simple implementation of a distributed system. In such systems servers (or nodes) are loosely coupled one with another and all of them carry all of the data. That is why there must be implemented 'data synchronization'. List<string> Nodes in this particular project is a list of IP addresses of the nodes (servers) that can be anywhere (or more servers can be run locally on different ports, as described in this article.
